### ISSUE TITLE
colour of font in menu is red

### ISSUE THREAD

**Issue by shermans** [shenzhuxi/readiator#6]
red is not good for read.
can we change it?

**Comment by nadia39** [comment]
can i help you to change this?

**Comment by shenzhuxi** [comment]
What colour is good for the menu?

**Comment by shermans** [comment]
个人观点.最传统的黑白配,应该是大部分人最习惯的配色
如果为了体现区别,目录可以灰一点,也能减少对正文的干扰,更容易深入阅读正文.
目录灰一丁点最好.
In my opinions. The best color for most person is white background and black words.
and black gray for menu.
